### ISSUE TITLE
Fix not necessary url_escape in cookie

### ISSUE THREAD

**Issue by norguhtar** [tarantool/http#114]
It already fixed in v1. but this bug still exist in v2. Can you fixed this?

https://github.com/tarantool/http/pull/82

**Comment by olegrok** [comment]
Hi!

But seems your patch (#82) is already applied - https://github.com/tarantool/http/blob/master/http/router/response.lua#L43

**Comment by norguhtar** [comment]
It not applied. See changes on 282 line. In you code you use  utils.uri_escape(value) before in 41 line
https://github.com/tarantool/http/pull/82/commits/accf960f35562e7ce9268d02782da6ef1853b091
