### ISSUE TITLE
req:request_line() doesn't return with the body

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/http#128]
Here is the test body
`{"user":{"email":"vmi@vmi.hu","password":"a1"}}`
req:request_line() returns with
`POST /ugyfelkapu-api/v1/login HTTP/1.1`
but the description says
> returns the request body.

I think something isn't good maybe the code or the desc. 
I need to get back the body and as a string.

**Comment by creadone** [comment]
> Here is the test body
> `{"user":{"email":"vmi@vmi.hu","password":"a1"}}`
> req:request_line() returns with
> `POST /ugyfelkapu-api/v1/login HTTP/1.1`
> but the description says
> 
> > returns the request body.
> 
> I think something isn't good maybe the code or the desc.
> I need to get back the body and as a string.

Most likely an error in the documentation. Try to use `req:read()`, it return request body.

**Comment by SWSAmor** [comment]
Thanks the `req:read()` is working. I misguided by the chunk parameter but it seems optional. Someone would correct the doc about request_line().
