### ISSUE TITLE
http.router module is missing ?

### ISSUE THREAD

**Issue by primadi** [tarantool/http#136]
when i am using router module:

local router = require('http.router')

in log file, error :

Start failed: /usr/share/tarantool/main.lua:6: module 'http.router' not found:
	no field package.preload['http.router']
	no file '/opt/tarantool/http/router.lua'
	no file '/opt/tarantool/http/router/init.lua'
	no file '/opt/tarantool/http/router.so'
	no file '/opt/tarantool/.rocks/share/tarantool/http/router.lua'
	no file '/opt/tarantool/.rocks/share/tarantool/http/router/init.lua'
	no file '/opt/.rocks/share/tarantool/http/router.lua'
	no file '/opt/.rocks/share/tarantool/http/router/init.lua'
	no file '/.rocks/share/tarantool/http/router.lua'
	no file '/.rocks/share/tarantool/http/router/init.lua'
	no file '/opt/tarantool/.rocks/lib/tarantool/http/router.so'
	no file '/opt/.rocks/lib/tarantool/http/router.so'
	no file '/.rocks/lib/tarantool/http/router.so'
	no file '/root/.luarocks/share/lua/5.1/http/router.lua'
	no file '/root/.luarocks/share/lua/5.1/http/router/init.lua'
	no file '/root/.luarocks/share/lua/http/router.lua'
	no file '/root/.luarocks/share/lua/http/router/init.lua'
	no file '/usr/local/share/tarantool/http/router.lua'
	no file '/usr/local/share/tarantool/http/router/init.lua'
	no file '/usr/share/tarantool/http/router.lua'
	no file '/usr/share/tarantool/http/router/init.lua'
	no file '/usr/local/share/lua/5.1/http/router.lua'
	no file '/usr/local/share/lua/5.1/http/router/init.lua'
	no file '/usr/share/lua/5.1/http/router.lua'
	no file '/usr/share/lua/5.1/http/router/init.lua'
	no file '/root/.luarocks/lib/lua/5.1/http/router.so'
	no file '/root/.luarocks/lib/lua/http/router.so'
	no file '/usr/local/lib64/tarantool/http/router.so'
	no file '/usr/local/lib/tarantool/http/router.so'
	no file '/usr/lib64/tarantool/http/router.so'
	no file '/usr/local/lib64/lua/5.1/http/router.so'
	no file '/usr/local/lib/lua/5.1/http/router.so'
	no file '/usr/lib64/lua/5.1/http/router.so'
	no file '/root/.luarocks/lib/lua/5.1/http.so'
	no file '/root/.luarocks/lib/lua/http.so'
	no file '/usr/local/lib64/tarantool/http.so'
	no file '/usr/local/lib/tarantool/http.so'
	no file '/usr/lib64/tarantool/http.so'
	no file '/usr/local/lib64/lua/5.1/http.so'
	no file '/usr/local/lib/lua/5.1/http.so'
	no file '/usr/lib64/lua/5.1/http.so'
	no file '/usr/local/lib/lua/5.1/http/router.so'
	no file '/usr/lib64/lua/5.1/http/router.so'
	no file '/root/.luarocks/lib/lua/5.1/http.so'
	no file '/root/.luarocks/lib/lua/http.so'
	no file '/usr/local/lib64/tarantool/http.so'
	no file '/usr/local/lib/tarantool/http.so'
	no file '/usr/lib64/tarantool/http.so'
	no file '/usr/local/lib64/lua/5.1/http.so'
	no file '/usr/local/lib/lua/5.1/http.so'
	no file '/usr/lib64/lua/5.1/http.so'

What is wrong with my code ?

I am using docker tarantool 2.9, same error when using docker tarantool 2.7

thanks.

**Comment by olegrok** [comment]
Hi! Seems you work with http module v1. See its readme [here](https://github.com/tarantool/http/blob/da1407c8e82dbdfd44abab8b1bb9860c217e7e22/README.md).
There is no http.router submodule in v1.

**Comment by primadi** [comment]
> Hi! Seems you work with http module v1. See its readme [here](https://github.com/tarantool/http/blob/da1407c8e82dbdfd44abab8b1bb9860c217e7e22/README.md).
> There is no http.router submodule in v1.

Thank you, i am using latest tarantool version (2.9) but http module is v1 ? this is misguided me.
