### ISSUE TITLE
HTTP cannot be built on old macs

### ISSUE THREAD

**Issue by scrumit** [tarantool/http#140]
This cannot be built on Macs that do not support AVX

The instructions here cause an "illegal hardware instruction" error in cmake.

**Comment by tsafin** [comment]
Sounds like you are complaining about `cmake` not the `tarantool/http` itself. From what source have you installed `cmake` to your system? Have you built it from source, or installed from `homebrew`?

**Comment by scrumit** [comment]
It's a late 2009 Mac mini running Catalina, so very old. I'll get a more modern machine...
