### ISSUE TITLE
Incorrect name of setcookie() method in documentation

### ISSUE THREAD

**Issue by ArcadyPerla** [tarantool/http#182]
Theris is incorrect method name in example in documentation. The right name setcookie() but in example write set_cookie()

**Comment by 0x501D** [comment]
Please specify where exactly this error occurs? I couldn't find any mention of the set_cookie() function anywhere.

**Comment by ArcadyPerla** [comment]
it's here:

<img width="1060" alt="Снимок экрана 2023-01-13 в 14 11 58" src="https://user-images.githubusercontent.com/10252266/212307469-ca88a085-e905-4070-a39f-338b00ced8fc.png">

**Comment by 0x501D** [comment]
Please clarify brunch.

**Comment by ArcadyPerla** [comment]
O, sorry! I found it in  Tarantool 1.6.5 version

**Comment by 0x501D** [comment]
Thanks for the reply, I think we can close this issue.
