### ISSUE TITLE
There is no distinction between PUT and DELETE methods

### ISSUE THREAD

**Issue by vitalygoryaev** [tarantool/http#25]
When using `method ` parameter in `route`, `PUT` and `DELETE` requests are routed to the same handler (which was defined first). If `DELETE` route was defined first then `PUT` request will be routed to `delete` handler.

Everything works fine for `GET` or `POST`

```
function post(self)
        return self:render({ json = 'post!'})
end

function put(self)
        return self:render({ json = 'put!'})
end

function delete(self)
        return self:render({ json = 'delete!'})
end

function get(self)
        return self:render({ json = 'get!'})
end

httpd:route(
    { path = '/test', method = 'DELETE' }, delete)
httpd:route(
    { path = '/test', method = 'PUT' }, put)
httpd:route(
    { path = '/test', method = 'POST' }, post)
httpd:route(
    { path = '/test', method = 'GET' }, get)
```

![image](https://cloud.githubusercontent.com/assets/3981764/15007416/7a15595a-11e1-11e6-8f99-3c0c3a464d49.png)

**Comment by bigbes** [comment]
Fixed, thank you!
