### ISSUE TITLE
Add support for allow_redirects in http.client.request()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/http#32]
See #28 for proposed API change:

```
http.client.request(method: string, url: string, opts: table) 
```

Continue to copy-cat [Python Requests API ](http://docs.python-requests.org/en/master/api/#requests.request) and add a new option:
- `opts = { allow_redirects = True }` - set to True if POST/PUT/DELETE redirect following is allowed.

**Comment by Totktonada** [comment]
The http client is now a built-in tarantool module. It has `follow_location` option (`true` by default), see https://github.com/tarantool/tarantool/pull/4119.
