### ISSUE TITLE
Sockets aren't closed implicitly

### ISSUE THREAD

**Issue by bigbes** [tarantool/http#38]
For example:
* https://github.com/tarantool/http/blob/fe5b3e55d1e216a6ecad2a7d8f8dacabb3dfb88a/http/client.lua#L161 - closed if everything went ok. In case of error - it's not closed implicitly.

**Comment by Totktonada** [comment]
The http client is now part of tarantool itself. The code was significantly reworked, so I doubt that this problem is actual. Feel free to open an issue against https://github.com/tarantool/tarantool if you'll find any problem with the built-in http client.
