### ISSUE TITLE
Confusing error reason when host could not be resolved

### ISSUE THREAD

**Issue by xv-marco-m** [tarantool/http#43]
When issuing an request to a host that cannot be resolved, reason returned is confusing.
Is it possible to have a better error reason such as "Could not resolve host"?

Example:
```
tarantool> http = require 'http.client'
tarantool> http.request('GET', 'http://any_hostname_that_cannot_be_resolved.com')
---
- status: 595
  reason: Invalid argument
...
```

**Comment by mpark86** [comment]
Hi, can I try taking a look at this?

**Comment by knazarov** [comment]
@xv-marco-m we actually now ship http.client within tarantool itself, and not with this module. See https://www.tarantool.io/en/doc/2.2/reference/reference_lua/http/

If you have a bug with that http client, you need to file that bug into the tarantool/tarantool repo

**Comment by knazarov** [comment]
As this issue has been long overdue, I'm closing it.
