### ISSUE TITLE
Content-Type not working?

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/http#45]
I set "Content-Type" to "application/vnd.api+json" in http.post opts.headers but it seems i got text/plain on the destination webserver. Is it possible or do i something wrong?

**Comment by Totktonada** [comment]
The default seems to be application/x-www-form-urlencoded. Are you sure you doing it right?

Try the following:

```
http = require('http.client')
http.post('http://example.org', '', {headers = {['Content-Type'] = 'application/vnd.api+json'}})
```

Wireshark shows me correct headers in the request.

**Comment by SWSAmor** [comment]
```
local options = {
        headers = {
            ['Content-Type'] = 'application/vnd.api+json'
        }
    }
local tresponse = http.post(url, body, options)
```

Hmm, I'm logged that with the nginx on the destination not with the wireshark:
```
192.168.164.126 -  [26/Jul/2017:09:56:09 +0200] "POST / HTTP/1.1" 200 5 "http://silverwing.tron.local:9333/" "Tarantool http client" "\"{    \\\"data\
\\": {        \\\"core\\\": \\\"string\\\"    }}\"" "text/plain"
```

**Comment by Totktonada** [comment]
The http client is now part of tarantool itself. I'll close this issue. Feel free to file an issue against https://github.com/tarantool/tarantool if you experience any problem with the built-in http client.
