### ISSUE TITLE
Unknown scheme: https

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/http#46]
https://tarantool.org/doc/1.7/reference/reference_lua/http.html is said:
> The http module, specifically the http.client submodule, provides the functionality of an HTTP client with support for HTTPS and keepalive. 

But it seems to me the https doesn't working, because i get:
`{"status":599,"reason":"Unknown scheme: https"}`

Did i something wrong?

**Comment by Totktonada** [comment]
`http.client` with https support is on-board since tarantool-1.7.4-151-g7e62ac79b. You can just use `local http = require('http.client').new()` without installing any extra packages.

**Comment by Totktonada** [comment]
I'll close this issue. Feel free to open an issue against https://github.com/tarantool/tarantool if you'll find a problem in the built-in http client.
