### ISSUE TITLE
Use new non-blocking `fio` module to read files

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/http#5]
Please use `fio` module to read files from the disk.

**Comment by yngvar-antonsson** [comment]
@ligurio wasn't that issue closed in 1.1.1?

**Comment by ligurio** [comment]
Yes, it was closed.
- 2.x.x (https://github.com/tarantool/http/commit/3ee593d3b95e80bf8a98df46c65bf80a9e82cbf3)
- 1.1.1 (https://github.com/tarantool/http/commit/5e479d030730cf007011e52732f818abcf356af1)
