### ISSUE TITLE
Non-cached Mode

### ISSUE THREAD

**Issue by cbalano** [tarantool/http#50]
Is there any way to run the http server in non-cached mode please?
By default, I have to restart tarantool after each and every modification to the LUA code.

**Comment by bigbes** [comment]
You should stop HTTP server, create new instance and bind all callbacks again (I'm using code like this):
```
local server = nil
if server then
    server:stop()
end
server = new_server()
```

**Comment by cbalano** [comment]
To clarify, I am looking for something similar to openresty's "lua_code_cache off;" directive.

You are suggesting creating a new http route that - when invoked - restarts the server?

**Comment by bigbes** [comment]
Can you provide an example of what you want? You're doing meta-programming or what?

> When turning off, every request served by ngx_lua will run in a separate Lua VM instance, starting from the 0.9.3 release.

No this behaviour in Tarantool at all.

**Comment by Totktonada** [comment]
Something like this should work:

```lua
local handlers = {}

local function set_http_handler(f)
    handlers.http_handler = f
end

httpd:route({path = '/', method = 'GET'}, function(req)
    return handlers.http_handler(req)
end)
```

So you always can call `set_http_handler()` to replace actual http handler implementation.

**Comment by Totktonada** [comment]
I suggest to highlight me (@Totktonada) in https://t.me/tarantool if you have further questions.
