### ISSUE TITLE
Not stop server: httpd:stop() not work

### ISSUE THREAD

**Issue by vvzvlad** [tarantool/http#57]
Test case:

> http_server = require('http.server').new(nil, 9999, {charset = "application/json"})
> http_server:route({ path = '/'}, function(req) return req:render{ json = {time = os.time()} } end)
> http_server:start()
> --request 
> http_server:stop()

After execute code, server remains work on port 9999. 

P.S. self.tcp_server:close() in stop() return true. Maybe, bug in socket lib?

**Comment by filonenko-mikhail** [comment]
Can not reproduce
