### ISSUE TITLE
Strange value of charset header: "charset=application/json"(json render)

### ISSUE THREAD

**Issue by vvzvlad** [tarantool/http#60]
Bug: if you use the library to give the client json (the code below), then the "charset" header will be equal to "application/json", which is undoubtedly an error.

```
function http_callback(params, req)
   local return_object = req:render{ json = {test="test"} }
   return return_object
end
```
Result:
![image](https://user-images.githubusercontent.com/3315944/44537058-8a7eac80-a706-11e8-8082-a853c96c505d.png)
Applications that expect this header to have a real response code page are breaking down.
If after the call to render redefine the header, then everything returns to normal:
```
function http_callback(params, req)
   local return_object = req:render{ json = {test="test"} }
   return_object.headers = return_object.headers or {}
   return_object.headers['charset'] = 'utf-8';
   return_object.headers['content-type'] = 'application/json';
   return return_object
end
```

Apparently, the error is in the lines [L373](https://github.com/tarantool/http/blob/3f0a967dcdce64e841013b3859bb9f5591997e4e/http/server.lua#L373)  и [L386](https://github.com/tarantool/http/blob/3f0a967dcdce64e841013b3859bb9f5591997e4e/http/server.lua#L386). I do not know how to fix it, since I do not know where "tx.httpd.options.charset" var comes from.

**Comment by filonenko-mikhail** [comment]
It seems that you redefine charset somewhere in init code. Something like

```
http_server = require('http.server').new(nil, 9999, {charset = "application/json"})
```
