### ISSUE TITLE
Can't debug route handler functions

### ISSUE THREAD

**Issue by d9k** [tarantool/http#73]
Tried IntelliJ IDEA + EmmyLua (https://www.tarantool.io/ru/doc/1.10/book/app_server/using_ide/), ZeroBrane Studio (I used `require('mobdebug').start('127.0.0.1')` code lines for ZBS).

Breakpoints doesn't work inside route handler functions code but work elsewhere.

**Comment by Totktonada** [comment]
The debugging facilities are not integrated with our cooperative multitasking. It is not a problem of the http server. I highlighted it in the relevant issue: https://github.com/tarantool/tarantool/issues/2731#issuecomment-1028598147.
