### ISSUE TITLE
uri_escape / to %2F in cookie path

### ISSUE THREAD

**Issue by denis-ignatenko** [tarantool/http#83]
Function uri_escape escape / to %2F. Affects setting cookie path. 

https://github.com/tarantool/http/blob/9047b514ea8ff9604e3844337067a85735650b9d/http/server.lua#L33

Possible fix:
res = string.gsub(str, '[^a-zA-Z0-9_/]'

**Comment by Totktonada** [comment]
PR #82 is about that as I see.

**Comment by Totktonada** [comment]
Now there is a `raw` option is the `:setcookie()` method. See 42e3002228a2e7c10ce45d34da39922d39cb5967 and f97518b6804f7c7e78056ff193acc49faaeecf57. I hope it resolves the problem. If it is not so or if you have more on the topic, don't hesitate to reopen the issue.
