### ISSUE TITLE
Not correct get param where param not exist

### ISSUE THREAD

**Issue by norguhtar** [tarantool/http#92]
**How reproduce**

1. Get in handler param from request:

``
test = req:param('test')
print(test)
``

2. Run query without this param but with other

test?ip=test

as result you get in test
``
{
  ip = "test"
}
``
I really think it not good idea return all params when i try get one param by index.

**Comment by Totktonada** [comment]
Tarantool 2.10.0-beta2-5-gdc19be406, http 1.2.0-5-g865bf76.

```lua
tarantool> http_server = require('http.server').new('127.0.0.1', 8080)
tarantool> http_server:route({path = '/', method = 'GET'}, function(req) return req:render({text = ('PARAM: %s\n'):format(req:param('test'))}) end)
tarantool> http_server:start()
```

```sh
$ curl 'http://localhost:8080?test=123'
PARAM: 123
$ curl 'http://localhost:8080?test=123&xxx=42'
PARAM: 123
$ curl 'http://localhost:8080?xxx=42'
PARAM: nil
$ curl 'http://localhost:8080'
PARAM: nil
```

It seems to work correctly, so I'll close the issue. Feel free to reopen with a reproducer if the problem still actual.
